workflows:
  ios-production:
    name: iOS Production
    max_build_duration: 120
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
    environment:
      node: 20.17.0
      groups:
        - ios
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install EAS CLI
        script: npm install -g eas-cli
      - name: Build iOS via EAS
        script: |
          eas build --platform ios --profile production --non-interactive
    artifacts:
      - "**/*.ipa"

  android-production:
    name: Android Production
    max_build_duration: 60
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
    environment:
      node: 20.17.0
      java: 17
      groups:
        - andriod
      android_signing:
        - hemensalon_keystore
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install EAS CLI
        script: npm install -g eas-cli
      - name: Build Android
        script: |
          unset ANDROID_SDK_ROOT
          export ANDROID_HOME=/Users/builder/Library/Android/sdk
          export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
          eas build --platform android --profile production --non-interactive --local --output app-release.aab
    artifacts:
      - app-release.aab
