export type Tip = { title: string; body: string }

const tr: Tip[] = [
  { title: '💜 Sadık Müşteri = Sürekli Gelir', body: 'En sadık 3 müşterinizi bu hafta arayın. Kısa bir ilgi, onları yıllarca bağlı tutar.' },
  { title: '📅 Boş Saatleri Doldurun', body: 'Bugün boş randevu varsa sosyal medyaya "Bugüne özel fırsat!" paylaşın. Hızlı dolar.' },
  { title: '⭐ Yorum İsteyin', body: 'Son 3 müşterinizden Google yorumu isteyin. Her yorum sizi yeni müşterilere taşır.' },
  { title: '📦 Paket Satışı Yapın', body: '"3 Al 1 Öde" paketi oluşturun. Paket alan müşteri %40 daha sık geri döner.' },
  { title: '🎂 Doğum Günü Sürprizi', body: 'Bu ay doğum günü olan müşterilerinize küçük bir sürpriz hazırlayın. Unutamazlar.' },
  { title: '📸 Dönüşüm Paylaşın', body: 'Bugün bir müşteri dönüşüm fotoğrafı paylaşın (izinli). En güçlü reklam budur.' },
  { title: '💳 Ön Ödeme Alın', body: 'Randevu ön ödemesi, iptal oranını %60 düşürür. Küçük bir tutar bile işe yarar.' },
  { title: '🛍 Çapraz Satış', body: 'Her randevuda bir ek ürün önerin. Bu alışkanlık ortalama gelirinizi %25 artırır.' },
  { title: '🏆 En İyi Çalışanı Kutlayın', body: 'Haftanın en iyi çalışanını takdir edin. Mutlu ekip, mutlu müşteri demek.' },
  { title: '💌 "Sizi Özledik" Mesajı', body: '60 gündür gelmeyen müşterilere Kampanya sekmesinden mesaj gönderin. Geri dönerler.' },
  { title: '💰 Fiyatlarınızı Gözden Geçirin', body: '6 ayda bir küçük fiyat artışı yapın. Müşteriler fark etmez ama geliriniz artar.' },
  { title: '⏰ Bekleme Süresi', body: 'Müşteri bekleme süresini 10 dakikanın altında tutun. Gecikmeler sadakat kaybettirir.' },
  { title: '👥 Referans Kampanyası', body: '"Arkadaşını getir, ikinize de %10 indirim" kampanyası başlatın. Ücretsiz büyüme.' },
  { title: '📦 Stoku Kontrol Edin', body: 'Stok sayfasını kontrol edin. Tükenmeye yakın ürünleri bugün sipariş edin.' },
  { title: '🔔 Hatırlatmaları Aktifleştirin', body: 'Otomatik randevu hatırlatmaları açık mı? Bildirimler sekmesinden kontrol edin.' },
  { title: '🌸 Mevsimsel Paket', body: 'Mevsim değişikliklerinde özel bakım paketleri sunun. Yaz/kış paketleri çok talep görür.' },
  { title: '🗺 Google Profiliniz', body: 'Google İşletme profilinizi bu ay güncellediniz mi? Çalışma saatlerinizi kontrol edin.' },
  { title: '📝 Müşteri Notları', body: 'Müşteri tercihlerini ve alerji notlarını kaydedin. Bu detaylar büyük fark yaratır.' },
  { title: '⚡ Hizmet Süresini Optimize Edin', body: 'En uzun hizmetinizde 10 dk kazanmak günde 1 ek randevu anlamına gelir.' },
  { title: '📊 Bu Haftayı Değerlendirin', body: 'Hangi hizmetler en çok talep gördü? Raporlar sekmesinden kontrol edin.' },
  { title: '📱 SMS Kısa & Net Olsun', body: 'Promosyon mesajınızın ilk 10 kelimesi en kritik kısım. Doğrudan konuya girin.' },
  { title: '🎁 Dijital Sadakat Kartı', body: '5 ziyarette 1 bedava hizmet sunun. Paketler sekmesinden kolayca oluşturabilirsiniz.' },
  { title: '👥 Ekip Buluşması', body: 'Haftada 30 dakika ekip toplantısı yapın. Küçük iyileştirmeler büyük kazanç sağlar.' },
  { title: '✨ Temizlik = Güven', body: 'Temiz ve düzenli salon, müşteri güveninin temelidir. Bugün bir gözden geçirin.' },
  { title: '🎯 İndirim Değil, Değer Ekleyin', body: 'İndirim yerine ücretsiz saç bakımı veya maske ekleyin. Daha değerli algılanır.' },
  { title: '📈 Pik Saatleri Yönetin', body: 'En yoğun saatlerinizde ek personel veya uzatılmış mesai planlayın.' },
  { title: '🔗 Online Rezervasyon Linki', body: 'Randevu linkinizi WhatsApp durumunuza ekleyin. Kolayca yeni müşteri kazanırsınız.' },
  { title: '👑 VIP Müşterilere Öncelik', body: 'VIP müşterileriniz gelirinizin %80\'ini oluşturur. Onlara ekstra özen gösterin.' },
  { title: '💬 Farkınızı Anlatın', body: 'Rakiplerinizden pahalıysanız fark yaratan şeyi vurgulayın: kalite, hijyen, deneyim.' },
  { title: '🎯 Haftalık Hedef Belirleyin', body: 'Bu hafta için küçük bir hedef koyun: 3 yeni müşteri veya 1 yeni hizmet. Başlayın!' },
]

const en: Tip[] = [
  { title: '💜 Loyal Customers = Steady Income', body: 'Call your top 3 loyal customers this week. A little attention keeps them for years.' },
  { title: '📅 Fill Empty Slots', body: 'If you have open slots today, post a "Today only — special offer!" on social media. It works fast.' },
  { title: '⭐ Ask for Reviews', body: 'Ask your last 3 customers for a Google review. Each review brings new clients.' },
  { title: '📦 Sell Packages', body: 'Create a "Buy 3 Get 1 Free" package. Package buyers return 40% more often.' },
  { title: '🎂 Birthday Surprise', body: 'Prepare a small surprise for customers with birthdays this month. They\'ll never forget it.' },
  { title: '📸 Share a Transformation', body: 'Post a before/after photo today (with permission). It\'s the most powerful ad you can run.' },
  { title: '💳 Take a Deposit', body: 'A small booking deposit cuts cancellations by 60%. Even a small amount makes a difference.' },
  { title: '🛍 Cross-Sell', body: 'Suggest one add-on per appointment. This habit grows your average revenue by 25%.' },
  { title: '🏆 Celebrate Your Best Staff', body: 'Recognise the employee of the week. Happy team = happy customers.' },
  { title: '💌 "We Miss You" Message', body: 'Send a campaign message to customers who haven\'t visited in 60 days. They come back.' },
  { title: '💰 Review Your Prices', body: 'A small price increase every 6 months goes unnoticed but grows your revenue.' },
  { title: '⏰ Watch Wait Times', body: 'Keep customer wait times under 10 minutes. Delays cost you loyalty.' },
  { title: '👥 Referral Campaign', body: '"Bring a friend — 10% off for both." Free growth with zero ad spend.' },
  { title: '📦 Check Your Stock', body: 'Open the Stock page. Order anything running low before it runs out.' },
  { title: '🔔 Enable Reminders', body: 'Are automatic appointment reminders turned on? Check the Notifications tab.' },
  { title: '🌸 Seasonal Package', body: 'Launch a seasonal care package at every season change. Summer/winter sets sell fast.' },
  { title: '🗺 Update Google Profile', body: 'Have you updated your Google Business profile this month? Check your opening hours.' },
  { title: '📝 Customer Notes', body: 'Record customer preferences and allergy notes. These details make a big difference.' },
  { title: '⚡ Optimise Service Time', body: 'Saving 10 minutes on your longest service means one extra appointment per day.' },
  { title: '📊 Review This Week', body: 'Which services were most popular? Check the Reports tab to find out.' },
  { title: '📱 Keep SMS Short', body: 'The first 10 words of your promo message are the most important. Get to the point.' },
  { title: '🎁 Digital Loyalty Card', body: 'Offer 1 free service after 5 visits. Create it easily in the Packages tab.' },
  { title: '👥 Team Meeting', body: 'Hold a 30-minute team huddle each week. Small improvements add up to big gains.' },
  { title: '✨ Cleanliness = Trust', body: 'A clean, tidy salon is the foundation of customer trust. Do a quick check today.' },
  { title: '🎯 Add Value, Not Discounts', body: 'Instead of discounts, add a free hair mask or massage. It feels more premium.' },
  { title: '📈 Manage Peak Hours', body: 'Plan extra staff or extended hours for your busiest periods.' },
  { title: '🔗 Online Booking Link', body: 'Add your booking link to your WhatsApp status. New clients will find you easily.' },
  { title: '👑 Prioritise VIP Customers', body: 'Your VIP clients generate 80% of revenue. Give them extra attention.' },
  { title: '💬 Communicate Your Difference', body: 'If you\'re priced higher than rivals, highlight your value: quality, hygiene, experience.' },
  { title: '🎯 Set a Weekly Goal', body: 'Set one small goal this week: 3 new clients or 1 new service. Then go for it!' },
]

const de: Tip[] = [
  { title: '💜 Treue Kunden = Stabiles Einkommen', body: 'Rufen Sie diese Woche Ihre 3 treuesten Kunden an. Etwas Aufmerksamkeit bindet sie für Jahre.' },
  { title: '📅 Leere Slots füllen', body: 'Haben Sie heute freie Termine? Posten Sie „Nur heute – Sonderangebot!" in sozialen Medien.' },
  { title: '⭐ Bewertungen anfragen', body: 'Bitten Sie Ihre letzten 3 Kunden um eine Google-Bewertung. Jede Bewertung bringt neue Kunden.' },
  { title: '📦 Pakete verkaufen', body: 'Erstellen Sie ein „3 kaufen, 1 gratis"-Paket. Kunden mit Paketen kommen 40 % öfter zurück.' },
  { title: '🎂 Geburtstagsüberraschung', body: 'Bereiten Sie für Kunden mit Geburtstag diesen Monat eine kleine Überraschung vor.' },
  { title: '📸 Transformation teilen', body: 'Teilen Sie heute ein Vorher/Nachher-Foto (mit Erlaubnis). Das ist die wirksamste Werbung.' },
  { title: '💳 Anzahlung verlangen', body: 'Eine kleine Buchungsanzahlung reduziert Absagen um 60 %. Selbst ein kleiner Betrag hilft.' },
  { title: '🛍 Cross-Selling', body: 'Empfehlen Sie pro Termin mindestens ein Zusatzprodukt. Dieser Habit steigert den Umsatz um 25 %.' },
  { title: '🏆 Besten Mitarbeiter auszeichnen', body: 'Würdigen Sie den Mitarbeiter der Woche. Zufriedenes Team = zufriedene Kunden.' },
  { title: '💌 „Wir vermissen Sie"-Nachricht', body: 'Senden Sie eine Kampagne an Kunden, die 60 Tage nicht da waren. Sie kommen zurück.' },
  { title: '💰 Preise überprüfen', body: 'Eine kleine Preiserhöhung alle 6 Monate fällt kaum auf, steigert aber den Umsatz.' },
  { title: '⏰ Wartezeit beachten', body: 'Halten Sie Wartezeiten unter 10 Minuten. Verzögerungen kosten Kundentreue.' },
  { title: '👥 Empfehlungsprogramm', body: '„Freund mitbringen – 10 % Rabatt für beide." Kostenloses Wachstum ohne Werbebudget.' },
  { title: '📦 Lager prüfen', body: 'Öffnen Sie die Lagerseite. Bestellen Sie Produkte, die zur Neige gehen, noch heute.' },
  { title: '🔔 Erinnerungen aktivieren', body: 'Sind automatische Terminerinnerungen eingeschaltet? Prüfen Sie die Benachrichtigungen.' },
  { title: '🌸 Saisonales Paket', body: 'Bieten Sie zu jedem Saisonwechsel ein Pflegepaket an. Sommer-/Winterpakete sind sehr gefragt.' },
  { title: '🗺 Google-Profil aktualisieren', body: 'Haben Sie Ihr Google-Unternehmensprofil diesen Monat aktualisiert? Öffnungszeiten prüfen.' },
  { title: '📝 Kundennotizen', body: 'Halten Sie Kundenpräferenzen und Allergiehinweise fest. Diese Details machen einen großen Unterschied.' },
  { title: '⚡ Servicezeit optimieren', body: '10 Minuten bei Ihrem längsten Service einsparen = 1 zusätzlicher Termin pro Tag.' },
  { title: '📊 Diese Woche auswerten', body: 'Welche Dienste waren am gefragtesten? Sehen Sie im Berichts-Tab nach.' },
  { title: '📱 SMS kurz & klar', body: 'Die ersten 10 Wörter Ihrer Promo-Nachricht sind entscheidend. Kommen Sie auf den Punkt.' },
  { title: '🎁 Digitale Treuekarte', body: 'Bieten Sie 1 kostenlosen Service nach 5 Besuchen an. Erstellen Sie es im Pakete-Tab.' },
  { title: '👥 Team-Meeting', body: 'Halten Sie wöchentlich ein 30-minütiges Team-Meeting. Kleine Verbesserungen summieren sich.' },
  { title: '✨ Sauberkeit = Vertrauen', body: 'Ein sauberer Salon ist die Grundlage des Kundenvertrauens. Machen Sie heute einen Rundgang.' },
  { title: '🎯 Wert statt Rabatt', body: 'Fügen Sie statt Rabatten eine kostenlose Haarkur hinzu. Das wirkt hochwertiger.' },
  { title: '📈 Stoßzeiten managen', body: 'Planen Sie für Ihre Stoßzeiten zusätzliches Personal oder längere Öffnungszeiten.' },
  { title: '🔗 Online-Buchungslink', body: 'Fügen Sie Ihren Buchungslink in Ihren WhatsApp-Status ein. Neue Kunden finden Sie leichter.' },
  { title: '👑 VIP-Kunden priorisieren', body: 'Ihre VIP-Kunden erzeugen 80 % des Umsatzes. Geben Sie ihnen besondere Aufmerksamkeit.' },
  { title: '💬 Ihren Mehrwert kommunizieren', body: 'Wenn Sie teurer sind: betonen Sie Qualität, Hygiene und Erfahrung als Unterschied.' },
  { title: '🎯 Wochenziel setzen', body: 'Setzen Sie sich ein kleines Ziel: 3 Neukunden oder 1 neuer Service. Jetzt starten!' },
]

const ar: Tip[] = [
  { title: '💜 الزبون الوفي = دخل ثابت', body: 'اتصل بأفضل 3 عملاء مخلصين لديك هذا الأسبوع. الاهتمام البسيط يربطهم بك لسنوات.' },
  { title: '📅 املأ المواعيد الفارغة', body: 'لديك مواعيد فارغة اليوم؟ انشر "عرض خاص لهذا اليوم فقط!" على وسائل التواصل الاجتماعي.' },
  { title: '⭐ اطلب تقييمات', body: 'اطلب من آخر 3 عملاء لديك تقييماً على Google. كل تقييم يجلب عملاء جدد.' },
  { title: '📦 بِع الباقات', body: 'أنشئ باقة "اشترِ 3 واحصل على 1 مجاناً". من يشتري الباقة يعود بنسبة 40% أكثر.' },
  { title: '🎂 مفاجأة عيد الميلاد', body: 'جهّز مفاجأة صغيرة لعملائك الذين لديهم أعياد ميلاد هذا الشهر. لن ينسوا ذلك.' },
  { title: '📸 شارك تحولاً', body: 'انشر صورة قبل وبعد اليوم (بإذن العميل). هذا أقوى إعلان يمكنك تقديمه.' },
  { title: '💳 خذ عربوناً', body: 'عربون حجز بسيط يقلل الإلغاءات بنسبة 60%. حتى مبلغ صغير يحدث فرقاً.' },
  { title: '🛍 البيع المتقاطع', body: 'اقترح منتجاً إضافياً في كل موعد. هذه العادة ترفع متوسط إيراداتك بنسبة 25%.' },
  { title: '🏆 كرّم أفضل موظف', body: 'احتفل بموظف الأسبوع. الفريق السعيد يعني عملاء سعداء.' },
  { title: '💌 رسالة "نشتاق إليكم"', body: 'أرسل حملة للعملاء الذين لم يزوروك منذ 60 يوماً من تبويب الحملات. سيعودون.' },
  { title: '💰 راجع أسعارك', body: 'زيادة صغيرة في الأسعار كل 6 أشهر لا يلاحظها أحد لكنها ترفع إيراداتك.' },
  { title: '⏰ راقب وقت الانتظار', body: 'أبقِ وقت انتظار العميل أقل من 10 دقائق. التأخير يُفقدك الولاء.' },
  { title: '👥 برنامج الإحالة', body: '"أحضر صديقاً واحصلا معاً على خصم 10%." نمو مجاني بدون ميزانية إعلانية.' },
  { title: '📦 تحقق من المخزون', body: 'افتح صفحة المخزون. اطلب المنتجات التي تنفد قبل أن ينتهي الوقت.' },
  { title: '🔔 فعّل التذكيرات', body: 'هل تذكيرات المواعيد التلقائية مفعّلة؟ تحقق من تبويب الإشعارات.' },
  { title: '🌸 باقة موسمية', body: 'أطلق باقة عناية موسمية مع كل تغير فصل. باقات الصيف/الشتاء تحظى بطلب كبير.' },
  { title: '🗺 حدّث ملفك على Google', body: 'هل حدّثت ملفك على Google Business هذا الشهر؟ تحقق من ساعات العمل.' },
  { title: '📝 ملاحظات العملاء', body: 'سجّل تفضيلات العملاء وملاحظات الحساسية. هذه التفاصيل تصنع فرقاً كبيراً.' },
  { title: '⚡ حسّن وقت الخدمة', body: 'توفير 10 دقائق في أطول خدمة لديك يعني موعداً إضافياً في اليوم.' },
  { title: '📊 قيّم هذا الأسبوع', body: 'ما الخدمات الأكثر طلباً؟ تحقق من تبويب التقارير لتعرف.' },
  { title: '📱 اجعل الرسائل قصيرة وواضحة', body: 'أول 10 كلمات في رسالتك الترويجية هي الأهم. اذهب مباشرة للنقطة.' },
  { title: '🎁 بطاقة ولاء رقمية', body: 'قدّم خدمة مجانية بعد 5 زيارات. أنشئها بسهولة من تبويب الباقات.' },
  { title: '👥 اجتماع الفريق', body: 'عقد اجتماعاً أسبوعياً لمدة 30 دقيقة. التحسينات الصغيرة تتراكم لتحقق نتائج كبيرة.' },
  { title: '✨ النظافة = الثقة', body: 'صالون نظيف ومرتب هو أساس ثقة العملاء. أجرِ جولة تفقدية اليوم.' },
  { title: '🎯 أضف قيمة لا خصماً', body: 'بدلاً من الخصم، أضف علاجاً مجانياً للشعر. يبدو أكثر قيمة وتميزاً.' },
  { title: '📈 أدر ساعات الذروة', body: 'خطّط لموظفين إضافيين أو ساعات ممتدة في أوقات الذروة.' },
  { title: '🔗 رابط الحجز الإلكتروني', body: 'أضف رابط حجزك إلى حالة WhatsApp. سيجدك العملاء الجدد بسهولة.' },
  { title: '👑 أولوية لعملاء VIP', body: 'عملاؤك المميزون يولّدون 80% من الإيرادات. امنحهم اهتماماً خاصاً.' },
  { title: '💬 أوضح ما يميزك', body: 'إذا كانت أسعارك أعلى، أبرز ما يجعلك مختلفاً: الجودة، النظافة، الخبرة.' },
  { title: '🎯 حدد هدفاً أسبوعياً', body: 'ضع هدفاً صغيراً هذا الأسبوع: 3 عملاء جدد أو خدمة جديدة واحدة. ابدأ الآن!' },
]

export const TIPS: Record<string, Tip[]> = { tr, en, de, ar }

export function getTipsForLanguage(lang: string): Tip[] {
  const base = lang.split('-')[0]
  return TIPS[base] ?? TIPS.tr
}
